// Getters
export const GET_ACTIVITIESDATA = "GET_ACTIVITIESDATA";
export const GET_POSITIONACCURACY = "GET_POSITIONACCURACY";
export const GET_COOKIECONSENTSTATUS = "GET_COOKIECONSENTSTATUS";
export const GET_FORCEUPDATEACTIVITIESDATA = "GET_FORCEUPDATEACTIVITIESDATA";
export const GET_SEARCHVISIBILITYSTATUS = "GET_SEARCHVISIBILITYSTATUS";
export const GET_USERSEARCH = "GET_USERSEARCH";
export const GET_SEARCHINPUT = "GET_SEARCHINPUT";
export const GET_FILTERACTIVITYLIST = "GET_FILTERACTIVITYLIST";
export const GET_FILTERACTIVITYLISTNU = "GET_FILTERACTIVITYLISTNU";

// Setters
export const SET_ACTIVITIES: string = "SET_ACTIVITIES";
export const SET_ACTIVITIESNU: string = "SET_ACTIVITIESNU";
export const SET_USERSEARCH: string = "SET_USERSEARCH";
export const SET_SEARCHINPUT: string = "SET_SEARCHINPUT";
export const SET_SEARCHSELECTVISIBLESTATUS: string =
  "SET_SEARCHSELECTVISIBLESTATUS";
export const SET_POSITIONACCURACY: string = "SET_POSITIONACCURACY";
export const SET_COOKIECONSENTSTATUS: string = "SET_COOKIECONSENTSTATUS";
export const SET_SEARCHVISIBILITYSTATUS: string = "SET_SEARCHVISIBILITYSTATUS";
